ALTER TABLE public.cab_buylist_items
ADD COLUMN IF NOT EXISTS grain TEXT,
ADD COLUMN IF NOT EXISTS width NUMERIC,
ADD COLUMN IF NOT EXISTS length NUMERIC,
ADD COLUMN IF NOT EXISTS thickness NUMERIC,
ADD COLUMN IF NOT EXISTS unit_qty NUMERIC;